aa = [30, 10, 20]
print("현재의 리스트 : %s" % aa)
aa.append(40)
print("append 후의 리스트 : %s" % aa)
aa.pop()
print("pop 후의 리스트 : %s" % aa)
aa.sort()
print("sort 후의 리스트 : %s" % aa)
aa.reverse()
print("reverse 후의 리스트 : %s" % aa)
aa.insert(2, 222)
print("insert(2, 222) 후의 리스트 : %s" % aa)
print("20값의 위치 : %d" % aa.index(20))
aa.remove(222)
print("remove(222) 후의 리스트 : %s" % aa)
aa.extend([77,88,77])
print("extend([77,88,77]) 후의 리스트 : %s" % aa)
print("77값의 개수 : %d" % aa.count(77))
